//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace ApiTiama.ServiceReference3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.tiama-inspection.com/", ConfigurationName="ServiceReference3.ServiceTM11Soap")]
    public interface ServiceTM11Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tiama-inspection.com/Counts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode Counts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tiama-inspection.com/Counts", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> CountsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tiama-inspection.com/GetAlarmsSinceLastQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetAlarmsSinceLastQuery();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tiama-inspection.com/GetAlarmsSinceLastQuery", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetAlarmsSinceLastQueryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tiama-inspection.com/GetAlarms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetAlarms();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tiama-inspection.com/GetAlarms", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetAlarmsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tiama-inspection.com/MountedMolds", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode MountedMolds();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tiama-inspection.com/MountedMolds", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> MountedMoldsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tiama-inspection.com/Measures", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode Measures();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tiama-inspection.com/Measures", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> MeasuresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tiama-inspection.com/CumulCounts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode CumulCounts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tiama-inspection.com/CumulCounts", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> CumulCountsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tiama-inspection.com/ReadenMolds", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ReadenMolds();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tiama-inspection.com/ReadenMolds", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ReadenMoldsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tiama-inspection.com/EjectedMolds", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode EjectedMolds();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tiama-inspection.com/EjectedMolds", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> EjectedMoldsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tiama-inspection.com/GetMoldsInSampleTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetMoldsInSampleTable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tiama-inspection.com/GetMoldsInSampleTable", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetMoldsInSampleTableAsync();
        
        // CODEGEN: Параметр "mountedMolds" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tiama-inspection.com/ChangeMountedMolds", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ApiTiama.ServiceReference3.ChangeMountedMoldsResponse ChangeMountedMolds(ApiTiama.ServiceReference3.ChangeMountedMoldsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tiama-inspection.com/ChangeMountedMolds", ReplyAction="*")]
        System.Threading.Tasks.Task<ApiTiama.ServiceReference3.ChangeMountedMoldsResponse> ChangeMountedMoldsAsync(ApiTiama.ServiceReference3.ChangeMountedMoldsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tiama-inspection.com/StopAllAutomaticEjectedMolds", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string StopAllAutomaticEjectedMolds();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tiama-inspection.com/StopAllAutomaticEjectedMolds", ReplyAction="*")]
        System.Threading.Tasks.Task<string> StopAllAutomaticEjectedMoldsAsync();
        
        // CODEGEN: Параметр "AddEjectedMolds" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tiama-inspection.com/AddEjectedMolds", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ApiTiama.ServiceReference3.AddEjectedMoldsResponse AddEjectedMolds(ApiTiama.ServiceReference3.AddEjectedMoldsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tiama-inspection.com/AddEjectedMolds", ReplyAction="*")]
        System.Threading.Tasks.Task<ApiTiama.ServiceReference3.AddEjectedMoldsResponse> AddEjectedMoldsAsync(ApiTiama.ServiceReference3.AddEjectedMoldsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tiama-inspection.com/EraseMoldsInSampleTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode EraseMoldsInSampleTable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tiama-inspection.com/EraseMoldsInSampleTable", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> EraseMoldsInSampleTableAsync();
        
        // CODEGEN: Параметр "ChangeMoldsInSampleTable" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlArrayAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tiama-inspection.com/ChangeMoldsInSampleTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ApiTiama.ServiceReference3.ChangeMoldsInSampleTableResponse ChangeMoldsInSampleTable(ApiTiama.ServiceReference3.ChangeMoldsInSampleTableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tiama-inspection.com/ChangeMoldsInSampleTable", ReplyAction="*")]
        System.Threading.Tasks.Task<ApiTiama.ServiceReference3.ChangeMoldsInSampleTableResponse> ChangeMoldsInSampleTableAsync(ApiTiama.ServiceReference3.ChangeMoldsInSampleTableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tiama-inspection.com/GetVersions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetVersions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tiama-inspection.com/GetVersions", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetVersionsAsync();
        
        // CODEGEN: Параметр "ChangeMoldsInSampleTable" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tiama-inspection.com/ChangeSamples", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ApiTiama.ServiceReference3.ChangeSamplesResponse ChangeSamples(ApiTiama.ServiceReference3.ChangeSamplesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tiama-inspection.com/ChangeSamples", ReplyAction="*")]
        System.Threading.Tasks.Task<ApiTiama.ServiceReference3.ChangeSamplesResponse> ChangeSamplesAsync(ApiTiama.ServiceReference3.ChangeSamplesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tiama-inspection.com/")]
    public partial class MountedMoldsXml : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Moule[] rootField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("mold", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Moule[] Root {
            get {
                return this.rootField;
            }
            set {
                this.rootField = value;
                this.RaisePropertyChanged("Root");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tiama-inspection.com/")]
    public partial class Moule : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int nbField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int nb {
            get {
                return this.nbField;
            }
            set {
                this.nbField = value;
                this.RaisePropertyChanged("nb");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tiama-inspection.com/")]
    public partial class PrelevementUnitaire : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int moldField;
        
        private CodeDetection sensorField;
        
        private int numberField;
        
        private ERemotingProvenance sourceField;
        
        private bool sourceFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int mold {
            get {
                return this.moldField;
            }
            set {
                this.moldField = value;
                this.RaisePropertyChanged("mold");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CodeDetection sensor {
            get {
                return this.sensorField;
            }
            set {
                this.sensorField = value;
                this.RaisePropertyChanged("sensor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ERemotingProvenance source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sourceSpecified {
            get {
                return this.sourceFieldSpecified;
            }
            set {
                this.sourceFieldSpecified = value;
                this.RaisePropertyChanged("sourceSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tiama-inspection.com/")]
    public enum CodeDetection {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item01,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("12")]
        Item12,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("14")]
        Item14,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("16")]
        Item16,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("17")]
        Item17,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("18")]
        Item18,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("16")]
        Item161,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("26")]
        Item26,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27")]
        Item27,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("28")]
        Item28,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("29")]
        Item29,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("30")]
        Item30,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("32")]
        Item32,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("35")]
        Item35,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("38")]
        Item38,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("39")]
        Item39,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("40")]
        Item40,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("41")]
        Item41,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("42")]
        Item42,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("43")]
        Item43,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("44")]
        Item44,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("46")]
        Item46,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("47")]
        Item47,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("49")]
        Item49,
        
        /// <remarks/>
        TableDeRejetsSystematiques,
        
        /// <remarks/>
        TableDePrelevements,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("54")]
        Item54,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("55")]
        Item55,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("56")]
        Item56,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("58")]
        Item58,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("66")]
        Item66,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("68)")]
        Item68,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("69")]
        Item69,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("70")]
        Item70,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("78")]
        Item78,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("79")]
        Item79,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("80")]
        Item80,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("85")]
        Item85,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("86")]
        Item86,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("87")]
        Item87,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("88")]
        Item88,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("91")]
        Item91,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("92")]
        Item92,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("93")]
        Item93,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("94")]
        Item94,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("95")]
        Item95,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("96")]
        Item96,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("97")]
        Item97,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("98")]
        Item98,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("100")]
        Item100,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("101")]
        Item101,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("102")]
        Item102,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("103")]
        Item103,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("104")]
        Item104,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("105")]
        Item105,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("106")]
        Item106,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("107")]
        Item107,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("108")]
        Item108,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("110")]
        Item110,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("112")]
        Item112,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("113")]
        Item113,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("114")]
        Item114,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("115")]
        Item115,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("116")]
        Item116,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("117")]
        Item117,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("118")]
        Item118,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("119")]
        Item119,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("120")]
        Item120,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("121")]
        Item121,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("130")]
        Item130,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("131")]
        Item131,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("132")]
        Item132,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("133")]
        Item133,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("140)")]
        Item140,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("141)")]
        Item141,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("255")]
        Item255,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tiama-inspection.com/")]
    public enum ERemotingProvenance {
        
        /// <remarks/>
        Toutes,
        
        /// <remarks/>
        TM11,
        
        /// <remarks/>
        SI,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tiama-inspection.com/")]
    public partial class MoulesPrelevesXml : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PrelevementUnitaire[] rootField;
        
        private string criteriaField;
        
        private EResetMode modeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("sample", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PrelevementUnitaire[] Root {
            get {
                return this.rootField;
            }
            set {
                this.rootField = value;
                this.RaisePropertyChanged("Root");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
                this.RaisePropertyChanged("criteria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public EResetMode mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
                this.RaisePropertyChanged("mode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tiama-inspection.com/")]
    public enum EResetMode {
        
        /// <remarks/>
        Normal,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Normal")]
        Normal1,
        
        /// <remarks/>
        OneShot,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tiama-inspection.com/")]
    public partial class PrelevementWS_1_0_9 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Moule moldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Moule mold {
            get {
                return this.moldField;
            }
            set {
                this.moldField = value;
                this.RaisePropertyChanged("mold");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
                this.RaisePropertyChanged("criteria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tiama-inspection.com/")]
    public partial class RejetMoule : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int nbField;
        
        private int reasonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int nb {
            get {
                return this.nbField;
            }
            set {
                this.nbField = value;
                this.RaisePropertyChanged("nb");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("reason");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tiama-inspection.com/")]
    public partial class MoulesEjectesXml : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RejetMoule[] rootField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("mold", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RejetMoule[] Root {
            get {
                return this.rootField;
            }
            set {
                this.rootField = value;
                this.RaisePropertyChanged("Root");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangeMountedMolds", WrapperNamespace="http://www.tiama-inspection.com/", IsWrapped=true)]
    public partial class ChangeMountedMoldsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.tiama-inspection.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ApiTiama.ServiceReference3.MountedMoldsXml mountedMolds;
        
        public ChangeMountedMoldsRequest() {
        }
        
        public ChangeMountedMoldsRequest(ApiTiama.ServiceReference3.MountedMoldsXml mountedMolds) {
            this.mountedMolds = mountedMolds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangeMountedMoldsResponse", WrapperNamespace="http://www.tiama-inspection.com/", IsWrapped=true)]
    public partial class ChangeMountedMoldsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.tiama-inspection.com/", Order=0)]
        public System.Xml.XmlNode ChangeMountedMoldsResult;
        
        public ChangeMountedMoldsResponse() {
        }
        
        public ChangeMountedMoldsResponse(System.Xml.XmlNode ChangeMountedMoldsResult) {
            this.ChangeMountedMoldsResult = ChangeMountedMoldsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddEjectedMolds", WrapperNamespace="http://www.tiama-inspection.com/", IsWrapped=true)]
    public partial class AddEjectedMoldsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.tiama-inspection.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ApiTiama.ServiceReference3.MoulesEjectesXml AddEjectedMolds;
        
        public AddEjectedMoldsRequest() {
        }
        
        public AddEjectedMoldsRequest(ApiTiama.ServiceReference3.MoulesEjectesXml AddEjectedMolds) {
            this.AddEjectedMolds = AddEjectedMolds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddEjectedMoldsResponse", WrapperNamespace="http://www.tiama-inspection.com/", IsWrapped=true)]
    public partial class AddEjectedMoldsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.tiama-inspection.com/", Order=0)]
        public string AddEjectedMoldsResult;
        
        public AddEjectedMoldsResponse() {
        }
        
        public AddEjectedMoldsResponse(string AddEjectedMoldsResult) {
            this.AddEjectedMoldsResult = AddEjectedMoldsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangeMoldsInSampleTable", WrapperNamespace="http://www.tiama-inspection.com/", IsWrapped=true)]
    public partial class ChangeMoldsInSampleTableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.tiama-inspection.com/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Root", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ApiTiama.ServiceReference3.PrelevementWS_1_0_9[] ChangeMoldsInSampleTable;
        
        public ChangeMoldsInSampleTableRequest() {
        }
        
        public ChangeMoldsInSampleTableRequest(ApiTiama.ServiceReference3.PrelevementWS_1_0_9[] ChangeMoldsInSampleTable) {
            this.ChangeMoldsInSampleTable = ChangeMoldsInSampleTable;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangeMoldsInSampleTableResponse", WrapperNamespace="http://www.tiama-inspection.com/", IsWrapped=true)]
    public partial class ChangeMoldsInSampleTableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.tiama-inspection.com/", Order=0)]
        public System.Xml.XmlNode ChangeMoldsInSampleTableResult;
        
        public ChangeMoldsInSampleTableResponse() {
        }
        
        public ChangeMoldsInSampleTableResponse(System.Xml.XmlNode ChangeMoldsInSampleTableResult) {
            this.ChangeMoldsInSampleTableResult = ChangeMoldsInSampleTableResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangeSamples", WrapperNamespace="http://www.tiama-inspection.com/", IsWrapped=true)]
    public partial class ChangeSamplesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.tiama-inspection.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ApiTiama.ServiceReference3.MoulesPrelevesXml ChangeMoldsInSampleTable;
        
        public ChangeSamplesRequest() {
        }
        
        public ChangeSamplesRequest(ApiTiama.ServiceReference3.MoulesPrelevesXml ChangeMoldsInSampleTable) {
            this.ChangeMoldsInSampleTable = ChangeMoldsInSampleTable;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangeSamplesResponse", WrapperNamespace="http://www.tiama-inspection.com/", IsWrapped=true)]
    public partial class ChangeSamplesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.tiama-inspection.com/", Order=0)]
        public System.Xml.XmlNode ChangeSamplesResult;
        
        public ChangeSamplesResponse() {
        }
        
        public ChangeSamplesResponse(System.Xml.XmlNode ChangeSamplesResult) {
            this.ChangeSamplesResult = ChangeSamplesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceTM11SoapChannel : ApiTiama.ServiceReference3.ServiceTM11Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceTM11SoapClient : System.ServiceModel.ClientBase<ApiTiama.ServiceReference3.ServiceTM11Soap>, ApiTiama.ServiceReference3.ServiceTM11Soap {
        
        public ServiceTM11SoapClient() {
        }
        
        public ServiceTM11SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceTM11SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTM11SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTM11SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.XmlNode Counts() {
            return base.Channel.Counts();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> CountsAsync() {
            return base.Channel.CountsAsync();
        }
        
        public System.Xml.XmlNode GetAlarmsSinceLastQuery() {
            return base.Channel.GetAlarmsSinceLastQuery();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetAlarmsSinceLastQueryAsync() {
            return base.Channel.GetAlarmsSinceLastQueryAsync();
        }
        
        public System.Xml.XmlNode GetAlarms() {
            return base.Channel.GetAlarms();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetAlarmsAsync() {
            return base.Channel.GetAlarmsAsync();
        }
        
        public System.Xml.XmlNode MountedMolds() {
            return base.Channel.MountedMolds();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> MountedMoldsAsync() {
            return base.Channel.MountedMoldsAsync();
        }
        
        public System.Xml.XmlNode Measures() {
            return base.Channel.Measures();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> MeasuresAsync() {
            return base.Channel.MeasuresAsync();
        }
        
        public System.Xml.XmlNode CumulCounts() {
            return base.Channel.CumulCounts();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> CumulCountsAsync() {
            return base.Channel.CumulCountsAsync();
        }
        
        public System.Xml.XmlNode ReadenMolds() {
            return base.Channel.ReadenMolds();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ReadenMoldsAsync() {
            return base.Channel.ReadenMoldsAsync();
        }
        
        public System.Xml.XmlNode EjectedMolds() {
            return base.Channel.EjectedMolds();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> EjectedMoldsAsync() {
            return base.Channel.EjectedMoldsAsync();
        }
        
        public System.Xml.XmlNode GetMoldsInSampleTable() {
            return base.Channel.GetMoldsInSampleTable();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetMoldsInSampleTableAsync() {
            return base.Channel.GetMoldsInSampleTableAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApiTiama.ServiceReference3.ChangeMountedMoldsResponse ApiTiama.ServiceReference3.ServiceTM11Soap.ChangeMountedMolds(ApiTiama.ServiceReference3.ChangeMountedMoldsRequest request) {
            return base.Channel.ChangeMountedMolds(request);
        }
        
        public System.Xml.XmlNode ChangeMountedMolds(ApiTiama.ServiceReference3.MountedMoldsXml mountedMolds) {
            ApiTiama.ServiceReference3.ChangeMountedMoldsRequest inValue = new ApiTiama.ServiceReference3.ChangeMountedMoldsRequest();
            inValue.mountedMolds = mountedMolds;
            ApiTiama.ServiceReference3.ChangeMountedMoldsResponse retVal = ((ApiTiama.ServiceReference3.ServiceTM11Soap)(this)).ChangeMountedMolds(inValue);
            return retVal.ChangeMountedMoldsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApiTiama.ServiceReference3.ChangeMountedMoldsResponse> ApiTiama.ServiceReference3.ServiceTM11Soap.ChangeMountedMoldsAsync(ApiTiama.ServiceReference3.ChangeMountedMoldsRequest request) {
            return base.Channel.ChangeMountedMoldsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApiTiama.ServiceReference3.ChangeMountedMoldsResponse> ChangeMountedMoldsAsync(ApiTiama.ServiceReference3.MountedMoldsXml mountedMolds) {
            ApiTiama.ServiceReference3.ChangeMountedMoldsRequest inValue = new ApiTiama.ServiceReference3.ChangeMountedMoldsRequest();
            inValue.mountedMolds = mountedMolds;
            return ((ApiTiama.ServiceReference3.ServiceTM11Soap)(this)).ChangeMountedMoldsAsync(inValue);
        }
        
        public string StopAllAutomaticEjectedMolds() {
            return base.Channel.StopAllAutomaticEjectedMolds();
        }
        
        public System.Threading.Tasks.Task<string> StopAllAutomaticEjectedMoldsAsync() {
            return base.Channel.StopAllAutomaticEjectedMoldsAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApiTiama.ServiceReference3.AddEjectedMoldsResponse ApiTiama.ServiceReference3.ServiceTM11Soap.AddEjectedMolds(ApiTiama.ServiceReference3.AddEjectedMoldsRequest request) {
            return base.Channel.AddEjectedMolds(request);
        }
        
        public string AddEjectedMolds(ApiTiama.ServiceReference3.MoulesEjectesXml AddEjectedMolds1) {
            ApiTiama.ServiceReference3.AddEjectedMoldsRequest inValue = new ApiTiama.ServiceReference3.AddEjectedMoldsRequest();
            inValue.AddEjectedMolds = AddEjectedMolds1;
            ApiTiama.ServiceReference3.AddEjectedMoldsResponse retVal = ((ApiTiama.ServiceReference3.ServiceTM11Soap)(this)).AddEjectedMolds(inValue);
            return retVal.AddEjectedMoldsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApiTiama.ServiceReference3.AddEjectedMoldsResponse> ApiTiama.ServiceReference3.ServiceTM11Soap.AddEjectedMoldsAsync(ApiTiama.ServiceReference3.AddEjectedMoldsRequest request) {
            return base.Channel.AddEjectedMoldsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApiTiama.ServiceReference3.AddEjectedMoldsResponse> AddEjectedMoldsAsync(ApiTiama.ServiceReference3.MoulesEjectesXml AddEjectedMolds) {
            ApiTiama.ServiceReference3.AddEjectedMoldsRequest inValue = new ApiTiama.ServiceReference3.AddEjectedMoldsRequest();
            inValue.AddEjectedMolds = AddEjectedMolds;
            return ((ApiTiama.ServiceReference3.ServiceTM11Soap)(this)).AddEjectedMoldsAsync(inValue);
        }
        
        public System.Xml.XmlNode EraseMoldsInSampleTable() {
            return base.Channel.EraseMoldsInSampleTable();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> EraseMoldsInSampleTableAsync() {
            return base.Channel.EraseMoldsInSampleTableAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApiTiama.ServiceReference3.ChangeMoldsInSampleTableResponse ApiTiama.ServiceReference3.ServiceTM11Soap.ChangeMoldsInSampleTable(ApiTiama.ServiceReference3.ChangeMoldsInSampleTableRequest request) {
            return base.Channel.ChangeMoldsInSampleTable(request);
        }
        
        public System.Xml.XmlNode ChangeMoldsInSampleTable(ApiTiama.ServiceReference3.PrelevementWS_1_0_9[] ChangeMoldsInSampleTable1) {
            ApiTiama.ServiceReference3.ChangeMoldsInSampleTableRequest inValue = new ApiTiama.ServiceReference3.ChangeMoldsInSampleTableRequest();
            inValue.ChangeMoldsInSampleTable = ChangeMoldsInSampleTable1;
            ApiTiama.ServiceReference3.ChangeMoldsInSampleTableResponse retVal = ((ApiTiama.ServiceReference3.ServiceTM11Soap)(this)).ChangeMoldsInSampleTable(inValue);
            return retVal.ChangeMoldsInSampleTableResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApiTiama.ServiceReference3.ChangeMoldsInSampleTableResponse> ApiTiama.ServiceReference3.ServiceTM11Soap.ChangeMoldsInSampleTableAsync(ApiTiama.ServiceReference3.ChangeMoldsInSampleTableRequest request) {
            return base.Channel.ChangeMoldsInSampleTableAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApiTiama.ServiceReference3.ChangeMoldsInSampleTableResponse> ChangeMoldsInSampleTableAsync(ApiTiama.ServiceReference3.PrelevementWS_1_0_9[] ChangeMoldsInSampleTable) {
            ApiTiama.ServiceReference3.ChangeMoldsInSampleTableRequest inValue = new ApiTiama.ServiceReference3.ChangeMoldsInSampleTableRequest();
            inValue.ChangeMoldsInSampleTable = ChangeMoldsInSampleTable;
            return ((ApiTiama.ServiceReference3.ServiceTM11Soap)(this)).ChangeMoldsInSampleTableAsync(inValue);
        }
        
        public System.Xml.XmlNode GetVersions() {
            return base.Channel.GetVersions();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetVersionsAsync() {
            return base.Channel.GetVersionsAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApiTiama.ServiceReference3.ChangeSamplesResponse ApiTiama.ServiceReference3.ServiceTM11Soap.ChangeSamples(ApiTiama.ServiceReference3.ChangeSamplesRequest request) {
            return base.Channel.ChangeSamples(request);
        }
        
        public System.Xml.XmlNode ChangeSamples(ApiTiama.ServiceReference3.MoulesPrelevesXml ChangeMoldsInSampleTable) {
            ApiTiama.ServiceReference3.ChangeSamplesRequest inValue = new ApiTiama.ServiceReference3.ChangeSamplesRequest();
            inValue.ChangeMoldsInSampleTable = ChangeMoldsInSampleTable;
            ApiTiama.ServiceReference3.ChangeSamplesResponse retVal = ((ApiTiama.ServiceReference3.ServiceTM11Soap)(this)).ChangeSamples(inValue);
            return retVal.ChangeSamplesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApiTiama.ServiceReference3.ChangeSamplesResponse> ApiTiama.ServiceReference3.ServiceTM11Soap.ChangeSamplesAsync(ApiTiama.ServiceReference3.ChangeSamplesRequest request) {
            return base.Channel.ChangeSamplesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApiTiama.ServiceReference3.ChangeSamplesResponse> ChangeSamplesAsync(ApiTiama.ServiceReference3.MoulesPrelevesXml ChangeMoldsInSampleTable) {
            ApiTiama.ServiceReference3.ChangeSamplesRequest inValue = new ApiTiama.ServiceReference3.ChangeSamplesRequest();
            inValue.ChangeMoldsInSampleTable = ChangeMoldsInSampleTable;
            return ((ApiTiama.ServiceReference3.ServiceTM11Soap)(this)).ChangeSamplesAsync(inValue);
        }
    }
}
